version: 0.0
os: linux
files:
  - source: /build/libs/pqrs_reporting_webapp.jar
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /scripts/configure_http_port.xsl
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
      runas: root
  ApplicationStart:   
    - location: scripts/start_application
      timeout: 300  
      runas: root